title: Um pouquinho da minha história na França
author: Rute Souza
email: rute@gmail.com
description: > # this means to ignore newlines until "baseurl:"
Eu vou lhes contar um pouco da minha experiência de viagem a França, como isso aconteceu. vou falar também sobre os principais desafios que encontrei aqui assim também quais as lições que levo disso tudo.  Venha comigo nessa leitura! :)  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
